name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lemonlot-frontend/**'  # Triggers only for changes in the frontend directory

jobs:
  run-frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # Checkout main branch for comparison code
      - name: Checkout main branch for comparison code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 1

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd lemonlot-frontend
          npm install

      # Generate coverage for the main branch
      - name: Generate coverage for the main branch
        run: |
          cd lemonlot-frontend
          npm run coverage
          # Upload the coverage report as an artifact
          mkdir -p coverage
          
          # Check if coverage-summary.json exists and move it; fallback to coverage-final.json
          if [ -f ./coverage/coverage-summary.json ]; then
            mv ./coverage/coverage-summary.json coverage/coverage-main.json
          elif [ -f ./coverage/coverage-final.json ]; then
            mv ./coverage/coverage-final.json coverage/coverage-main.json
          else
            echo "No coverage summary file found!"
            exit 1
          fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-main
          path: ${{ github.workspace }}/lemonlot-frontend/coverage/coverage-main.json

      # Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # Ensure coverage directory exists
      - name: Create coverage directory
        run: mkdir -p lemonlot-frontend/coverage

      # Generate coverage for the PR branch
      - name: Generate coverage for the PR branch
        run: |
          cd lemonlot-frontend
          npm install
          npm run coverage
          # Check if coverage files exist
          if [ -f ./coverage/coverage-summary.json ]; then
            mv ./coverage/coverage-summary.json coverage/coverage-pr.json
          elif [ -f ./coverage/coverage-final.json ]; then
            mv ./coverage/coverage-final.json coverage/coverage-pr.json
          else
            echo "No coverage summary file found for PR!"
            exit 1
          fi

      # Download the coverage artifact from the main branch
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-main
          path: lemonlot-frontend/coverage

      # Report Coverage
      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: './lemonlot-frontend'
          json-summary-path: './coverage/coverage-pr.json'
          json-summary-compare-path: './coverage/coverage-main.json'
          name: 'Vitest Frontend Coverage Report'
